"""name index

Revision ID: 5bde69cdba71
Revises: 24452fbacc04
Create Date: 2026-02-11 15:14:05.282180

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = '5bde69cdba71'
down_revision: Union[str, None] = '24452fbacc04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hooligaps_history', schema=None) as batch_op:
        batch_op.create_index('idx_name', ['first_name', 'last_name'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hooligaps_history', schema=None) as batch_op:
        batch_op.drop_index('idx_name')

    # ### end Alembic commands ###
