"""init

Revision ID: 24452fbacc04
Revises:
Create Date: 2026-02-11 11:47:14.827222

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '24452fbacc04'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'hooligaps_history',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('date', sa.Date(), nullable=False),
        sa.Column('first_name', sa.String(length=150), nullable=False),
        sa.Column('last_name', sa.String(length=150), nullable=False),
        sa.PrimaryKeyConstraint('id'),
    )
    with op.batch_alter_table('hooligaps_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_hooligaps_history_date'), ['date'], unique=False)
        batch_op.create_index(
            batch_op.f('ix_hooligaps_history_first_name'), ['first_name'], unique=False
        )
        batch_op.create_index(
            batch_op.f('ix_hooligaps_history_last_name'), ['last_name'], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hooligaps_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_hooligaps_history_last_name'))
        batch_op.drop_index(batch_op.f('ix_hooligaps_history_first_name'))
        batch_op.drop_index(batch_op.f('ix_hooligaps_history_date'))

    op.drop_table('hooligaps_history')
    # ### end Alembic commands ###
